name: 'build'
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - dev
      - 'releases/*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install
        run: |
          npm install
      - name: run all
        run: |
          npm run all
